// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
import Permissions from './permissions';

export const RESOURCE_KEYS = {
    ABOUT: 'about',
    BILLING: {
        SUBSCRIPTION: 'billing.subscription',
        BILLING_HISTORY: 'billing.billing_history',
        COMPANY_INFORMATION: 'billing.company_information',
        PAYMENT_INFORMATION: 'billing.payment_information',
    },
    USER_MANAGEMENT: {
        USERS: 'user_management.users',
        GROUPS: 'user_management.groups',
        TEAMS: 'user_management.teams',
        CHANNELS: 'user_management.channels',
        PERMISSIONS: 'user_management.permissions',
        SYSTEM_ROLES: 'user_management.system_roles',
    }
}

export const ResourceToSysConsolePermissionsTable: Record<string, string[]> = {
    [RESOURCE_KEYS.ABOUT]: [Permissions.SYSCONSOLE_READ_ABOUT, Permissions.SYSCONSOLE_WRITE_ABOUT],
    [RESOURCE_KEYS.BILLING.SUBSCRIPTION]: [Permissions.SYSCONSOLE_READ_BILLING_SUBSCRIPTION, Permissions.SYSCONSOLE_WRITE_BILLING_SUBSCRIPTION],
    [RESOURCE_KEYS.BILLING.BILLING_HISTORY]: [Permissions.SYSCONSOLE_READ_BILLING_BILLING_HISTORY, Permissions.SYSCONSOLE_WRITE_BILLING_BILLING_HISTORY],
    [RESOURCE_KEYS.BILLING.COMPANY_INFORMATION]: [Permissions.SYSCONSOLE_READ_BILLING_COMPANY_INFORMATION, Permissions.SYSCONSOLE_WRITE_BILLING_COMPANY_INFORMATION],
    [RESOURCE_KEYS.BILLING.PAYMENT_INFORMATION]: [Permissions.SYSCONSOLE_READ_BILLING_PAYMENT_INFORMATION, Permissions.SYSCONSOLE_WRITE_BILLING_PAYMENT_INFORMATION], 
    reporting: [Permissions.SYSCONSOLE_READ_REPORTING, Permissions.SYSCONSOLE_WRITE_REPORTING],
    [RESOURCE_KEYS.USER_MANAGEMENT.USERS]: [Permissions.SYSCONSOLE_READ_USERMANAGEMENT_USERS, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_USERS],
    [RESOURCE_KEYS.USER_MANAGEMENT.GROUPS]: [Permissions.SYSCONSOLE_READ_USERMANAGEMENT_GROUPS, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_GROUPS],
    [RESOURCE_KEYS.USER_MANAGEMENT.TEAMS]:[Permissions.SYSCONSOLE_READ_USERMANAGEMENT_TEAMS, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_TEAMS],
    [RESOURCE_KEYS.USER_MANAGEMENT.CHANNELS]:[Permissions.SYSCONSOLE_READ_USERMANAGEMENT_CHANNELS, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_CHANNELS],
    [RESOURCE_KEYS.USER_MANAGEMENT.PERMISSIONS]: [Permissions.SYSCONSOLE_READ_USERMANAGEMENT_PERMISSIONS, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_PERMISSIONS],
    [RESOURCE_KEYS.USER_MANAGEMENT.SYSTEM_ROLES]:[Permissions.SYSCONSOLE_READ_USERMANAGEMENT_SYSTEM_ROLES, Permissions.SYSCONSOLE_WRITE_USERMANAGEMENT_SYSTEM_ROLES],
    environment: [Permissions.SYSCONSOLE_READ_ENVIRONMENT, Permissions.SYSCONSOLE_WRITE_ENVIRONMENT],
    site: [Permissions.SYSCONSOLE_READ_SITE, Permissions.SYSCONSOLE_WRITE_SITE],
    authentication: [Permissions.SYSCONSOLE_READ_AUTHENTICATION, Permissions.SYSCONSOLE_WRITE_AUTHENTICATION],
    plugins: [Permissions.SYSCONSOLE_READ_PLUGINS, Permissions.SYSCONSOLE_WRITE_PLUGINS],
    integrations: [Permissions.SYSCONSOLE_READ_INTEGRATIONS, Permissions.SYSCONSOLE_WRITE_INTEGRATIONS],
    compliance: [Permissions.SYSCONSOLE_READ_COMPLIANCE, Permissions.SYSCONSOLE_WRITE_COMPLIANCE],
    experimental: [Permissions.SYSCONSOLE_READ_EXPERIMENTAL, Permissions.SYSCONSOLE_WRITE_EXPERIMENTAL],
};